"""
A dictionary that maps EDBs by name to the
"Network Location Names" that they serve.

Intended to be complete (with respect to both
EDBs and Network Location Names)
"""

edb_to_locations = {
    "EA Networks": [
        "Ashburton",
        "Ashburton/ Mid Canterbury",
        "EA Networks",
        "EASH Mid Canterbury",
    ],
    "Counties Power": ["Counties", "Counties Power", "COUP", "COUP Counties"],
    "Vector (Auckland)": [
        "Auckland Central and Manukau",
        "Auckland",
        "Auckland (VECT)",
        "Auckland Central and Manukau",
        "Auckland Vector",
        "VECT",
        "VECT Auck C",
        "Vector",
        "Vector (Auckland Central/Manukau)",
        "Vector Central",
    ],
    "Vector (Northern)": [
        "Auckland North / West",
        "Auckland UNL",
        "UNET",
        "UNET Auck N",
        "UNET Northern",
        "Vector (Auckland North/West)",
        "Vector (Northern)",
        "Vector Northern",
        "Waitemata",
        "Waitemata(Vector)",
    ],
    "Buller Electricity": ["Buller", "BUEL Buller", "Buller Electricity"],
    "Orion New Zealand Ltd": [
        "Central Canterbury (Zone B)",
        "Christchurch",
        "Canterbury",
        "Christchurch",
        "Orion",
        "ORON Canterbury",
    ],
    "Centralines Ltd": ["Central Hawkes Bay", "Centralines", "CHBP Central Hawkes Bay"],
    "Aurora Energy (Clyde/Cromwell)": [
        "Central Otago (Clyde/Cromwell - Small Capacity)",
        "Central Otago (Clyde/Cromwell)",
        "Central Otago (Clyde/Cromwell - Small Capacity)",
        "Central Otago (Clyde/Cromwell 8 kVA)",
        "Central Otago 8 kVA",
        "Clyde/Cromwell & District (Small Capacity)",
        "Central Otago",
        "Central Otago (Clyde/Cromwell)",
        "Clyde / Cromwell (15kVA & 8kVA)",
        "Cromwell",
        "DUNE Clyde",
    ],
    "Aurora Energy (Queenstown)": [
        "Central Otago (Queenstown - Small Capacity)",
        "Central Otago (Queenstown)",
        "Central Otago (Queenstown - Small Capacity)",
        "Central Otago (Queenstown 8 kVA)",
        "Queenstown & Districts (Small Capacity)",
        "Queenstown 8 kVA",
        "Queenstown",
        "Central Otago FKN",
        "DUNE Queenstown",
        "Queenstown (15kVA & 8kVA)",
    ],
    "Horizon Energy Distribution": [
        "Eastern Bay of Plenty (Urban)",
        "Bay of Plenty Urban",
        "HEDL - Urban",
        "Horizon (Urban)",
        "Horizon Energy (Urban)",
        "Eastern Bay of Plenty (Urban)",
        "Eastern Bay of Plenty (Rural)",
        "Eastern Bay of Plenty",
        "HEDL EBOP",
        "Horizon",
        "Whakatane",
    ],
    "Firstlight Network": [
        "Eastland (High Density)",
        "Eastland (Low Density)",
        "EAST",
        "Eastland",
        "Eastland Energy",
        "East Coast",
        "EAST East Coast HD",
    ],
    "Network Tasman Ltd": ["Golden Bay", "Tasman", "TASM Tasman", "Tasman"],
    "Unison Networks Ltd (Hawke's Bay)": [
        "Hawkes Bay",
        "HAWK - Hawkes Bay",
        "HAWK Hawkes Bay",
        "Hawkes Bay",
        "HAWKES BAY (ELEC)",
        "Hawkes Bay FHL-RDF",
        "Unison - Hawkes Bay",
        "Unison (Hawkes Bay)",
    ],
    "Electra": [
        "Horowhenua/Kapiti",
        "ELEC",
        "ELEC Kapiti",
        "Electra",
        "Horowhenua/ Kapiti",
        "Horowhenua/Kapiti",
        "Kapiti and Horowhenua",
        "Kapiti/Horowhenua",
        "Levin",
    ],
    "Electricity Invercargill Ltd": [
        "Invercargill",
        "ELIN Invercargill 20",
        "Invercargill - 20kVA",
        "Invercargill 20 kVA",
        "Invercargill Residential (20kVa)",
    ],
    "MainPower NZ Ltd": [
        "Kaiapoi",
        "Kaiapoi",
        "North Canterbury",
        "MainPower",
        "MPOW Mainpower",
        "North Canterbury",
    ],
    "The Lines Company": [
        "King Country (High Density)",
        "King Country",
        "King Country LINE",
        "King Country Residential High Density",
        "LINE",
        "LINE King Country (High Density)",
        "The Lines Company (High Density)",
    ],
    "Powerco (Manawatu)": [
        "Manawatu",
        "Palmerston North",
        "POCOPNTH Manawatu",
        "Powerco (exCentralPower) Bunnythorpe & Linton",
        "West - Manawatu",
    ],
    "Marlborough Lines Ltd": [
        "Marlborough",
        "MARL",
        "MARL Marlborough",
        "Marlborough Lines",
    ],
    "Nelson Electricity Ltd": ["Nelson", "NELS Nelson"],
    "Top Energy": [
        "Northern Northland",
        "Far North",
        "Northern Northland",
        "Top Energy",
        "TOPE Far North",
    ],
    "Northpower": [
        "Northland",
        "North Power",
        "Northland",
        "Northpower",
        "NPOW Northland",
        "Whangarei",
    ],
    "OtagoNet": ["Otago", "OtagoNet", "OTPO Otago"],
    "Unison Networks Ltd (Rotorua)": [
        "Rotorua",
        "HAWKROT Rotorua",
        "Rotorua",
        "Unison - Rotorua",
    ],
    "Unison Networks Ltd (Taupo)": [
        "Rotorua",
        "Taupo",
        "HAWK - Rotorua & Taupo",
        "Rotorua & Taupo",
        "Rotorua and Taupo",
        "Rotorua/Taupo",
        "Taupo/Rotorua - Spot",
        "Unison (Rotorua & Taupo)",
        "Unison (Rotorua/Taupo)",
        "Taupo",
        "HAWKTPO Taupo",
        "Taupo",
        "Unison - Taupo",
    ],
    "Alpine Energy": [
        "South Canterbury (Urban - LCA)",
        "ALPE Sth Cant LCA",
        "Alpine (LCA)",
        "Alpine Energy (Urban - LCA)",
        "Alpine Energy LCA",
        "South Canterbury - LCA",
        "South Canterbury (Urban - LCA)",
        "South Canterbury (Urban)",
        "South Canterbury LCA",
        "Timaru - LCA",
    ],
    "Scanpower Ltd": [
        "Southern Hawkes Bay",
        "SCAN Sth Hawkes Bay",
        "Scanpower",
        "Southern Hawkes Bay",
        "Southern Hawkes Bay (SCAN)",
    ],
    "The Power Company Ltd (Urban)": [
        "Southland (Urban - Small Capacity)",
        "Southland (Urban)",
        "Southland (Urban - Small Capacity)",
        "Southland (Urban 8kVA)",
        "Southland (Urban) 8kVA",
        "Southland Urban 8 kVa",
        "The Power Company (Urban - 8 kVA)",
        "The Power Company Urban 8 kVA (Southland Urban - Small Capacity)",
        "TPCO Southland Urban 08",
        "Southland (Urban)",
        "The Power Company Ltd (Urban)",
        "Southland Urban 20 kVa",
        "The Power Company (Urban)",
        "The Power Company Urban 20 kVA (Southland Urban)",
        "TPCO Southland Urban 20",
    ],
    "Powerco (Taranaki)": ["Taranaki (Zone A)", "New Plymouth", "POCOTARA Taranaki A"],
    "Powerco (Western A)": [
        "Manawatu",
        "Taranaki (Zone A)",
        "Wanganui",
        "POCO West A",
        "Powerco (Western Region A)",
        "PowerCo West (Zone A)",
        "Powerco West A",
        "Taranaki (Zone A)",
        "Wanganui",
        "Powerco (Taranaki) Zone A",
        "Taranaki (Zone A)",
        "West - Taranaki",
        "Wanganui",
        "POCOWANG Wanganui",
        "Whanganui",
    ],
    "Powerco (Western B)": [
        "Taranaki (Zone B)",
        "Marton/Bulls",
        "Raetihi area",
        "Taihape Waiouru",
        "Powerco (Taranaki) Zone B",
        "Taranaki (Zone B)",
        "West - Rural",
        "Taranaki (Zone B)",
        "Tararua",
        "Raetihi area",
        "Taihape Waiouru",
        "POCOTARB Taranaki B",
        "Tararua",
        "Powerco (exCentralPower) Mangamaire",
        "Tararua",
        "Tararua",
        "Wairarapa",
        "Wairarapa",
        "West - Wairarapa",
        "Taranaki (Zone B)",
        "Tararua",
        "Wairarapa",
        "Marton/Bulls",
        "Raetihi area",
        "POCO West B",
        "Taranaki (Zone B)",
        "Tararua",
        "Wairarapa",
        "Marton/Bulls",
        "Raetihi area",
        "Taihape Waiouru",
        "Hawera/Rangitikei & Wairarapa/Tararua",
        "Powerco (Western Region B)",
        "Powerco West B",
        "PowerCo West (Zone B)",
        "Marton/Bulls",
        "POCOMTN Marton",
        "Waverley area",
        "POCO West B - Waverley",
        "POCOTARB Taranaki B - Waverley area",
        "Powerco (Taranaki B) Waverley area",
        "Powerco (Western Region B) Waverley area",
        "Powerco West (Zone B) - Waverley Area",
        "South Taranaki/Rangitikei : Waverley area",
        "Waverley (Taranaki B)",
        "Waverley area",
    ],
    "WEL Networks": ["Waikato", "Hamilton", "WAIK Hamilton", "Waikato", "WEL Networks"],
    "Waipa Networks Ltd": [
        "Waipa",
        "Waipa (Rural)",
        "South Waikato (Waipa)",
        "WAIP Sth Waikato",
        "Waipa",
        "Waipa Networks",
    ],
    "Wellington Electricity": [
        "Wellington",
        "CKHK Wgtn",
        "Wellington",
        "Wellington (CKHK)",
        "Wellington Electricity",
    ],
    "Westpower Ltd": [
        "Westland",
        "Greymouth",
        "West Coast",
        "Westland",
        "Westpower",
        "WPOW WestCoast",
    ],
    "Aurora Energy (Dunedin)": [
        "Dunedin",
        "Aurora (Dunedin)",
        "Aurora Dunedin 15kVa",
        "Aurora Energy (Dunedin) 15 kVA",
        "Dunedin",
        "Dunedin - SHSD15",
        "Dunedin (15 kVA)",
    ],
    "Network Waitaki": [
        "Waitaki",
        "Network Waitaki",
        "North Otago",
        "Oamaru",
        "Waitaki",
        "WATA North Otago",
    ],
    "The Power Company Ltd": [
        "Southland (Urban)",
        "Southland (Urban - Small Capacity)",
        "Southland (Urban)",
        "Southland (Urban - Small Capacity)",
        "Southland (Urban 8kVA)",
        "Southland (Urban) 8kVA",
        "Southland Urban 8 kVa",
        "The Power Company (Urban - 8 kVA)",
        "The Power Company Urban 8 kVA (Southland Urban - Small Capacity)",
        "TPCO Southland Urban 08",
        "The Power Company Ltd (Urban)",
        "Southland Urban 20 kVa",
        "The Power Company (Urban)",
        "The Power Company Urban 20 kVA (Southland Urban)",
        "TPCO Southland Urban 20",
    ],
    "Stewart Island Electrical Supply Authority": [],
}
