"""
Test the energy consumption profiles generated by the user answers classes.
"""

from pytest import approx, raises

from app.constants import DAYS_IN_YEAR
from app.models.user_answers import (
    CooktopAnswers,
    HeatingAnswers,
    HouseholdEnergyProfileAnswers,
    YourHomeAnswers,
)
from app.services.configuration import (
    get_default_cooktop_answers,
    get_default_driving_answers,
    get_default_heating_answers,
    get_default_hot_water_answers,
    get_default_household_energy_profile,
    get_default_plans,
    get_default_solar_answers,
    get_default_your_home_answers,
)

# This is used as follows:
# assert cooktop_energy_use.natural_gas_kwh == approx(
#     expected_kwh, rel=1e-2


def test_create_household_profile_answers():
    """
    Test the creation of a household profile answers object.
    """
    household_profile = HouseholdEnergyProfileAnswers(
        your_home=get_default_your_home_answers(),
        heating=get_default_heating_answers(),
        hot_water=get_default_hot_water_answers(),
        cooktop=get_default_cooktop_answers(),
        driving=get_default_driving_answers(),
        solar=get_default_solar_answers(),
    )
    assert household_profile.your_home.people_in_house == 4
    assert household_profile.your_home.postcode == "0000"
    assert household_profile.driving.vehicle_type == "Petrol"


def test_cooking_energy_usage():
    """
    Test the energy usage pattern for cooking.
    """
    your_home = get_default_your_home_answers()
    cooktop = get_default_cooktop_answers()

    # Modeled energy use in kWh for each cooktop type. This is based
    # on a linearized energy use model that preserves the average
    # household energy use for cooking. (See 'Cooking' sheet of
    # supporting workbook.)
    expected_energy_use = {
        "Electric induction": [159, 239, 319, 398, 478, 558],
        "Piped gas": [412, 618, 824, 1030, 1236, 1442],
        "Bottled gas": [412, 618, 824, 1030, 1236, 1442, 1648],
        "Electric (coil or ceramic)": [176, 264, 352, 440, 528, 617],
    }

    # Expected field values based on cooktop type
    expected_values = {
        "Electric induction": {
            "elx_connection_days": DAYS_IN_YEAR,
            "flexible_kwh": 0,
            "natural_gas_kwh": 0,
            "lpg_kwh": 0,
            "natural_gas_connection_days": 0,
            "lpg_tanks_rental_days": 0,
        },
        "Piped gas": {
            "elx_connection_days": 0,
            "day_kwh": 0,
            "flexible_kwh": 0,
            "lpg_kwh": 0,
            "natural_gas_connection_days": DAYS_IN_YEAR,
            "lpg_tanks_rental_days": 0,
        },
        "Bottled gas": {
            "elx_connection_days": 0,
            "day_kwh": 0,
            "flexible_kwh": 0,
            "natural_gas_connection_days": 0,
            "lpg_tanks_rental_days": DAYS_IN_YEAR,
        },
        "Electric (coil or ceramic)": {
            "elx_connection_days": DAYS_IN_YEAR,
            "flexible_kwh": 0,
            "natural_gas_kwh": 0,
            "lpg_kwh": 0,
            "natural_gas_connection_days": 0,
            "lpg_tanks_rental_days": 0,
        },
    }

    for cooktop_type, energy_use_values in expected_energy_use.items():
        cooktop.cooktop = cooktop_type
        for i, expected_kwh in enumerate(energy_use_values):
            your_home.people_in_house = i + 1
            cooktop_energy_use = cooktop.energy_usage_pattern(your_home)

            # Assertions for expected energy usage (day_kwh, lpg_kwh, natural_gas_kwh)
            if cooktop_type in ["Electric induction", "Electric (coil or ceramic)"]:
                assert cooktop_energy_use.day_kwh == approx(expected_kwh, rel=1e-2)
            elif cooktop_type == "Piped gas":
                assert cooktop_energy_use.natural_gas_kwh == approx(
                    expected_kwh, rel=1e-2
                )
            elif cooktop_type == "Bottled gas":
                assert cooktop_energy_use.lpg_kwh == approx(expected_kwh, rel=1e-2)

            # General assertions based on the cooktop type
            for field, expected_value in expected_values[cooktop_type].items():
                assert (
                    getattr(cooktop_energy_use, field) == expected_value
                ), f"{field} failed for {cooktop_type}"


def test_space_heating_energy_usage():
    """
    Test the energy usage pattern for space heating.
    """
    profile = get_default_household_energy_profile()
    plans = get_default_plans()

    main_heating_sources = [
        "Heat pump",
        "Electric heater",
        "Wood burner",
        "Piped gas heater",
        "Bottled gas heater",
    ]

    expected_energy_cost = {
        "Heat pump": {"electricity_variable_cost_nzd": 246.58797380448001},
        "Electric heater": {"electricity_variable_cost_nzd": 739.76392141344},
        "Wood burner": {"wood_variable_cost_nzd": 227.08219547520002},
        "Piped gas heater": {"natural_gas_variable_cost_nzd": 420.320409894},
        "Bottled gas heater": {"lpg_variable_cost_nzd": 932.3470910376001},
    }

    for main_heating_source in main_heating_sources:
        heating = HeatingAnswers(
            main_heating_source=main_heating_source,
            alternative_main_heating_source="Heat pump",
            heating_during_day="5-7 days a week",
            insulation_quality="Moderately insulated",
            user_provided=False,
        )
        # determine energy usage pattern
        heating_energy_use = heating.energy_usage_pattern(profile["your_home"])

        # calculate costs by fuel
        _, heating_electricity_variable_cost = plans["electricity_plan"].calculate_cost(
            heating_energy_use
        )
        _, heating_lpg_variable_cost = plans["lpg_plan"].calculate_cost(
            heating_energy_use
        )
        _, heating_natural_gas_variable_cost = plans["natural_gas_plan"].calculate_cost(
            heating_energy_use
        )
        _, heating_wood_variable_cost = plans["wood_price"].calculate_cost(
            heating_energy_use
        )

        # compare with expected costs
        expected_electricity = expected_energy_cost[main_heating_source].get(
            "electricity_variable_cost_nzd", 0
        )
        expected_lpg = expected_energy_cost[main_heating_source].get(
            "lpg_variable_cost_nzd", 0
        )
        expected_natural_gas = expected_energy_cost[main_heating_source].get(
            "natural_gas_variable_cost_nzd", 0
        )
        expected_wood = expected_energy_cost[main_heating_source].get(
            "wood_variable_cost_nzd", 0
        )
        assert heating_electricity_variable_cost == approx(expected_electricity)
        assert heating_lpg_variable_cost == approx(expected_lpg)
        assert heating_natural_gas_variable_cost == approx(expected_natural_gas)
        assert heating_wood_variable_cost == approx(expected_wood)


def test_invalid_cooktop_type():
    """
    Test that an invalid cooktop type raises a ValueError.
    """
    your_home = YourHomeAnswers(
        people_in_house=3,
        postcode="1234",
        disconnect_gas=True,
        user_provided=True,
    )
    cooktop_answers = CooktopAnswers(
        cooktop="Piped gas",
        alternative_cooktop="Piped gas",
        user_provided=False,
    )
    setattr(cooktop_answers, "cooktop", "Invalid type")
    setattr(cooktop_answers, "alternative_cooktop", "Invalid type")
    with raises(ValueError, match="Unknown cooktop type: Invalid type"):
        cooktop_answers.energy_usage_pattern(your_home)
