"""
A mapping from territorial authorities to climate zones.
Note that there are two territorial authorities that are split
between climate zones.
"""

ta_to_climate_zone = {
    "Far North District": "Northland",
    "Whangarei District": "Northland",
    "Kaipara District": "Northland",
    "Rodney District": "Auckland",
    "North Shore City": "Auckland",
    "Waitakere City": "Auckland",
    "Auckland City": "Auckland",
    "Manukau City": "Auckland",
    "Papakura District": "Auckland",
    "Franklin District": "Auckland",
    "Thames-Coromandel District": "Auckland",
    "Hauraki District": "Hamilton",
    "Waikato District": "Hamilton",
    "Matamata-Piako District": "Hamilton",
    "Hamilton City": "Hamilton",
    "Waipa District": "Hamilton",
    "Otorohanga District": "Hamilton",
    "South Waikato District": "Hamilton",
    "Waitomo District": "Hamilton",
    "Taupo District": "Taupo",
    "Western Bay of Plenty District": "Bay of Plenty",
    "Tauranga City": "Bay of Plenty",
    "Whakatane District": "Bay of Plenty",
    "Kawerau District": "Bay of Plenty",
    "Opotiki District": "Bay of Plenty",
    "Rotorua District": "Rotorua",
    "Ruapehu District": "Taupo",
    "New Plymouth District": "New Plymouth",
    "Stratford District": "New Plymouth",
    "South Taranaki District": "New Plymouth",
    "Whanganui District": "New Plymouth",
    "Gisborne District": "East Coast",
    "Wairoa District": "East Coast",
    "Hastings District": "East Coast",
    "Napier City": "East Coast",
    "Central Hawke's Bay District": "East Coast",
    "Manawatu District": "Manawatu",
    "Palmerston North City": "Manawatu",
    "Horowhenua District": "Manawatu",
    "Kapiti Coast District": "Manawatu",
    "Tararua District": "Wairarapa",
    "Upper Hutt City": "Wairarapa",
    "Masterton District": "Wairarapa",
    "Carterton District": "Wairarapa",
    "South Wairarapa District": "Wairarapa",
    "Porirua City": "Wellington",
    "Hutt City": "Wellington",
    "Wellington City": "Wellington",
    "Tasman District": "Nelson-Marlborough",
    "Nelson City": "Nelson-Marlborough",
    "Marlborough District": "Nelson-Marlborough",
    "Kaikoura District": "Nelson-Marlborough",
    "Buller District": "West Coast",
    "Grey District": "West Coast",
    "Westland District": "West Coast",
    "Hurunui District": "Christchurch",
    "Waimakariri District": "Christchurch",
    "Christchurch City": "Christchurch",
    "Selwyn District": "Christchurch",
    "Ashburton District": "Christchurch",
    "Timaru District": "Christchurch",
    "Waimate District": "Christchurch",
    "Queenstown-Lakes District": "Queenstown-Lakes",
    "Mackenzie District": "Central Otago",
    "Central Otago District": "Central Otago",
    "Waitaki District": "Dunedin",
    "Dunedin City": "Dunedin",
    "Clutha District": "Dunedin",
    "Southland District": "Invercargill",
    "Gore District": "Invercargill",
    "Invercargill City": "Invercargill",
    "Ōtorohanga District": "Hamilton",
    "Ōpōtiki District": "Bay of Plenty",
    "Rangitikei District": "Manawatu",
    "Lower Hutt City": "Wellington",
    "Chatham Islands Territory": "East Coast",
    "Auckland": "Auckland",
    "Area Outside Territorial Authority": "Outside TA",
}
